// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FlatAbandonedCheckout
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class AbandonedCheckout : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"AbandonedCheckout\",\"namespace\":\"FlatAbandonedCheckout\",\"" +
				"fields\":[{\"name\":\"AbandonedCheckoutUrl\",\"type\":[\"null\",\"string\"]},{\"name\":\"Buyer" +
				"AcceptsMarketing\",\"type\":[\"null\",\"boolean\"]},{\"name\":\"CartToken\",\"type\":[\"null\"," +
				"\"string\"]},{\"name\":\"ClosedAt\",\"type\":[\"null\",\"long\"]},{\"name\":\"CompletedAt\",\"typ" +
				"e\":[\"null\",\"long\"]},{\"name\":\"CreatedAt\",\"type\":[\"null\",\"long\"]},{\"name\":\"Currenc" +
				"y\",\"type\":[\"null\",\"string\"]},{\"name\":\"CustomerLocale\",\"type\":[\"null\",\"string\"]}," +
				"{\"name\":\"DeviceId\",\"type\":[\"null\",\"long\"]},{\"name\":\"Email\",\"type\":[\"null\",\"strin" +
				"g\"]},{\"name\":\"Gateway\",\"type\":[\"null\",\"string\"]},{\"name\":\"LandingSite\",\"type\":[\"" +
				"null\",\"string\"]},{\"name\":\"LocationId\",\"type\":[\"null\",\"long\"]},{\"name\":\"Note\",\"ty" +
				"pe\":[\"null\",\"string\"]},{\"name\":\"Phone\",\"type\":[\"null\",\"string\"]},{\"name\":\"Presen" +
				"tmentCurrency\",\"type\":[\"null\",\"string\"]},{\"name\":\"ReferringSite\",\"type\":[\"null\"," +
				"\"string\"]},{\"name\":\"SourceName\",\"type\":[\"null\",\"string\"]},{\"name\":\"SubtotalPrice" +
				"\",\"type\":[\"null\",\"double\"]},{\"name\":\"TaxesIncluded\",\"type\":[\"null\",\"boolean\"]},{" +
				"\"name\":\"Token\",\"type\":[\"null\",\"string\"]},{\"name\":\"TotalDiscounts\",\"type\":[\"null\"" +
				",\"double\"]},{\"name\":\"TotalDuties\",\"type\":[\"null\",\"double\"]},{\"name\":\"TotalLineIt" +
				"emsPrice\",\"type\":[\"null\",\"double\"]},{\"name\":\"TotalPrice\",\"type\":[\"null\",\"double\"" +
				"]},{\"name\":\"TotalTax\",\"type\":[\"null\",\"double\"]},{\"name\":\"TotalWeight\",\"type\":[\"n" +
				"ull\",\"double\"]},{\"name\":\"AbandonedCheckoutId\",\"type\":[\"null\",\"long\"]},{\"name\":\"U" +
				"pdatedAt\",\"type\":[\"null\",\"long\"]},{\"name\":\"UserId\",\"type\":[\"null\",\"long\"]},{\"nam" +
				"e\":\"TenantId\",\"type\":\"int\"},{\"name\":\"StoreId\",\"type\":\"int\"},{\"name\":\"Remark\",\"ty" +
				"pe\":[\"null\",\"string\"]},{\"name\":\"Status\",\"type\":[\"null\",\"string\"]},{\"name\":\"Assig" +
				"neeId\",\"type\":\"int\"},{\"name\":\"CallTimes\",\"type\":\"int\"},{\"name\":\"AbandonedOrderId" +
				"\",\"type\":[\"null\",\"string\"]},{\"name\":\"StatusId\",\"type\":\"int\"},{\"name\":\"RemarkId\"," +
				"\"type\":\"int\"},{\"name\":\"AssigningDate\",\"type\":[\"null\",\"long\"]},{\"name\":\"ShippingA" +
				"ddressId\",\"type\":[\"null\",\"long\"]},{\"name\":\"BillingAddressId\",\"type\":[\"null\",\"lon" +
				"g\"]},{\"name\":\"AdditionalInfo\",\"type\":[\"null\",\"string\"]},{\"name\":\"FullBillingAddr" +
				"ess\",\"type\":[\"null\",\"string\"]},{\"name\":\"FullShippingAddress\",\"type\":[\"null\",\"str" +
				"ing\"]},{\"name\":\"CustomerName\",\"type\":[\"null\",\"string\"]},{\"name\":\"CreationTime\",\"" +
				"type\":[\"null\",\"long\"]},{\"name\":\"Products\",\"type\":[\"null\",\"string\"]}]}");
		private string _AbandonedCheckoutUrl;
		private System.Nullable<bool> _BuyerAcceptsMarketing;
		private string _CartToken;
		private System.Nullable<long> _ClosedAt;
		private System.Nullable<long> _CompletedAt;
		private System.Nullable<long> _CreatedAt;
		private string _Currency;
		private string _CustomerLocale;
		private System.Nullable<long> _DeviceId;
		private string _Email;
		private string _Gateway;
		private string _LandingSite;
		private System.Nullable<long> _LocationId;
		private string _Note;
		private string _Phone;
		private string _PresentmentCurrency;
		private string _ReferringSite;
		private string _SourceName;
		private System.Nullable<double> _SubtotalPrice;
		private System.Nullable<bool> _TaxesIncluded;
		private string _Token;
		private System.Nullable<double> _TotalDiscounts;
		private System.Nullable<double> _TotalDuties;
		private System.Nullable<double> _TotalLineItemsPrice;
		private System.Nullable<double> _TotalPrice;
		private System.Nullable<double> _TotalTax;
		private System.Nullable<double> _TotalWeight;
		private System.Nullable<long> _AbandonedCheckoutId;
		private System.Nullable<long> _UpdatedAt;
		private System.Nullable<long> _UserId;
		private int _TenantId;
		private int _StoreId;
		private string _Remark;
		private string _Status;
		private int _AssigneeId;
		private int _CallTimes;
		private string _AbandonedOrderId;
		private int _StatusId;
		private int _RemarkId;
		private System.Nullable<long> _AssigningDate;
		private System.Nullable<long> _ShippingAddressId;
		private System.Nullable<long> _BillingAddressId;
		private string _AdditionalInfo;
		private string _FullBillingAddress;
		private string _FullShippingAddress;
		private string _CustomerName;
		private System.Nullable<long> _CreationTime;
		private string _Products;
		public virtual Schema Schema
		{
			get
			{
				return AbandonedCheckout._SCHEMA;
			}
		}
		public string AbandonedCheckoutUrl
		{
			get
			{
				return this._AbandonedCheckoutUrl;
			}
			set
			{
				this._AbandonedCheckoutUrl = value;
			}
		}
		public System.Nullable<bool> BuyerAcceptsMarketing
		{
			get
			{
				return this._BuyerAcceptsMarketing;
			}
			set
			{
				this._BuyerAcceptsMarketing = value;
			}
		}
		public string CartToken
		{
			get
			{
				return this._CartToken;
			}
			set
			{
				this._CartToken = value;
			}
		}
		public System.Nullable<long> ClosedAt
		{
			get
			{
				return this._ClosedAt;
			}
			set
			{
				this._ClosedAt = value;
			}
		}
		public System.Nullable<long> CompletedAt
		{
			get
			{
				return this._CompletedAt;
			}
			set
			{
				this._CompletedAt = value;
			}
		}
		public System.Nullable<long> CreatedAt
		{
			get
			{
				return this._CreatedAt;
			}
			set
			{
				this._CreatedAt = value;
			}
		}
		public string Currency
		{
			get
			{
				return this._Currency;
			}
			set
			{
				this._Currency = value;
			}
		}
		public string CustomerLocale
		{
			get
			{
				return this._CustomerLocale;
			}
			set
			{
				this._CustomerLocale = value;
			}
		}
		public System.Nullable<long> DeviceId
		{
			get
			{
				return this._DeviceId;
			}
			set
			{
				this._DeviceId = value;
			}
		}
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				this._Email = value;
			}
		}
		public string Gateway
		{
			get
			{
				return this._Gateway;
			}
			set
			{
				this._Gateway = value;
			}
		}
		public string LandingSite
		{
			get
			{
				return this._LandingSite;
			}
			set
			{
				this._LandingSite = value;
			}
		}
		public System.Nullable<long> LocationId
		{
			get
			{
				return this._LocationId;
			}
			set
			{
				this._LocationId = value;
			}
		}
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				this._Note = value;
			}
		}
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				this._Phone = value;
			}
		}
		public string PresentmentCurrency
		{
			get
			{
				return this._PresentmentCurrency;
			}
			set
			{
				this._PresentmentCurrency = value;
			}
		}
		public string ReferringSite
		{
			get
			{
				return this._ReferringSite;
			}
			set
			{
				this._ReferringSite = value;
			}
		}
		public string SourceName
		{
			get
			{
				return this._SourceName;
			}
			set
			{
				this._SourceName = value;
			}
		}
		public System.Nullable<double> SubtotalPrice
		{
			get
			{
				return this._SubtotalPrice;
			}
			set
			{
				this._SubtotalPrice = value;
			}
		}
		public System.Nullable<bool> TaxesIncluded
		{
			get
			{
				return this._TaxesIncluded;
			}
			set
			{
				this._TaxesIncluded = value;
			}
		}
		public string Token
		{
			get
			{
				return this._Token;
			}
			set
			{
				this._Token = value;
			}
		}
		public System.Nullable<double> TotalDiscounts
		{
			get
			{
				return this._TotalDiscounts;
			}
			set
			{
				this._TotalDiscounts = value;
			}
		}
		public System.Nullable<double> TotalDuties
		{
			get
			{
				return this._TotalDuties;
			}
			set
			{
				this._TotalDuties = value;
			}
		}
		public System.Nullable<double> TotalLineItemsPrice
		{
			get
			{
				return this._TotalLineItemsPrice;
			}
			set
			{
				this._TotalLineItemsPrice = value;
			}
		}
		public System.Nullable<double> TotalPrice
		{
			get
			{
				return this._TotalPrice;
			}
			set
			{
				this._TotalPrice = value;
			}
		}
		public System.Nullable<double> TotalTax
		{
			get
			{
				return this._TotalTax;
			}
			set
			{
				this._TotalTax = value;
			}
		}
		public System.Nullable<double> TotalWeight
		{
			get
			{
				return this._TotalWeight;
			}
			set
			{
				this._TotalWeight = value;
			}
		}
		public System.Nullable<long> AbandonedCheckoutId
		{
			get
			{
				return this._AbandonedCheckoutId;
			}
			set
			{
				this._AbandonedCheckoutId = value;
			}
		}
		public System.Nullable<long> UpdatedAt
		{
			get
			{
				return this._UpdatedAt;
			}
			set
			{
				this._UpdatedAt = value;
			}
		}
		public System.Nullable<long> UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				this._UserId = value;
			}
		}
		public int TenantId
		{
			get
			{
				return this._TenantId;
			}
			set
			{
				this._TenantId = value;
			}
		}
		public int StoreId
		{
			get
			{
				return this._StoreId;
			}
			set
			{
				this._StoreId = value;
			}
		}
		public string Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				this._Remark = value;
			}
		}
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				this._Status = value;
			}
		}
		public int AssigneeId
		{
			get
			{
				return this._AssigneeId;
			}
			set
			{
				this._AssigneeId = value;
			}
		}
		public int CallTimes
		{
			get
			{
				return this._CallTimes;
			}
			set
			{
				this._CallTimes = value;
			}
		}
		public string AbandonedOrderId
		{
			get
			{
				return this._AbandonedOrderId;
			}
			set
			{
				this._AbandonedOrderId = value;
			}
		}
		public int StatusId
		{
			get
			{
				return this._StatusId;
			}
			set
			{
				this._StatusId = value;
			}
		}
		public int RemarkId
		{
			get
			{
				return this._RemarkId;
			}
			set
			{
				this._RemarkId = value;
			}
		}
		public System.Nullable<long> AssigningDate
		{
			get
			{
				return this._AssigningDate;
			}
			set
			{
				this._AssigningDate = value;
			}
		}
		public System.Nullable<long> ShippingAddressId
		{
			get
			{
				return this._ShippingAddressId;
			}
			set
			{
				this._ShippingAddressId = value;
			}
		}
		public System.Nullable<long> BillingAddressId
		{
			get
			{
				return this._BillingAddressId;
			}
			set
			{
				this._BillingAddressId = value;
			}
		}
		public string AdditionalInfo
		{
			get
			{
				return this._AdditionalInfo;
			}
			set
			{
				this._AdditionalInfo = value;
			}
		}
		public string FullBillingAddress
		{
			get
			{
				return this._FullBillingAddress;
			}
			set
			{
				this._FullBillingAddress = value;
			}
		}
		public string FullShippingAddress
		{
			get
			{
				return this._FullShippingAddress;
			}
			set
			{
				this._FullShippingAddress = value;
			}
		}
		public string CustomerName
		{
			get
			{
				return this._CustomerName;
			}
			set
			{
				this._CustomerName = value;
			}
		}
		public System.Nullable<long> CreationTime
		{
			get
			{
				return this._CreationTime;
			}
			set
			{
				this._CreationTime = value;
			}
		}
		public string Products
		{
			get
			{
				return this._Products;
			}
			set
			{
				this._Products = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.AbandonedCheckoutUrl;
			case 1: return this.BuyerAcceptsMarketing;
			case 2: return this.CartToken;
			case 3: return this.ClosedAt;
			case 4: return this.CompletedAt;
			case 5: return this.CreatedAt;
			case 6: return this.Currency;
			case 7: return this.CustomerLocale;
			case 8: return this.DeviceId;
			case 9: return this.Email;
			case 10: return this.Gateway;
			case 11: return this.LandingSite;
			case 12: return this.LocationId;
			case 13: return this.Note;
			case 14: return this.Phone;
			case 15: return this.PresentmentCurrency;
			case 16: return this.ReferringSite;
			case 17: return this.SourceName;
			case 18: return this.SubtotalPrice;
			case 19: return this.TaxesIncluded;
			case 20: return this.Token;
			case 21: return this.TotalDiscounts;
			case 22: return this.TotalDuties;
			case 23: return this.TotalLineItemsPrice;
			case 24: return this.TotalPrice;
			case 25: return this.TotalTax;
			case 26: return this.TotalWeight;
			case 27: return this.AbandonedCheckoutId;
			case 28: return this.UpdatedAt;
			case 29: return this.UserId;
			case 30: return this.TenantId;
			case 31: return this.StoreId;
			case 32: return this.Remark;
			case 33: return this.Status;
			case 34: return this.AssigneeId;
			case 35: return this.CallTimes;
			case 36: return this.AbandonedOrderId;
			case 37: return this.StatusId;
			case 38: return this.RemarkId;
			case 39: return this.AssigningDate;
			case 40: return this.ShippingAddressId;
			case 41: return this.BillingAddressId;
			case 42: return this.AdditionalInfo;
			case 43: return this.FullBillingAddress;
			case 44: return this.FullShippingAddress;
			case 45: return this.CustomerName;
			case 46: return this.CreationTime;
			case 47: return this.Products;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.AbandonedCheckoutUrl = (System.String)fieldValue; break;
			case 1: this.BuyerAcceptsMarketing = (System.Nullable<bool>)fieldValue; break;
			case 2: this.CartToken = (System.String)fieldValue; break;
			case 3: this.ClosedAt = (System.Nullable<long>)fieldValue; break;
			case 4: this.CompletedAt = (System.Nullable<long>)fieldValue; break;
			case 5: this.CreatedAt = (System.Nullable<long>)fieldValue; break;
			case 6: this.Currency = (System.String)fieldValue; break;
			case 7: this.CustomerLocale = (System.String)fieldValue; break;
			case 8: this.DeviceId = (System.Nullable<long>)fieldValue; break;
			case 9: this.Email = (System.String)fieldValue; break;
			case 10: this.Gateway = (System.String)fieldValue; break;
			case 11: this.LandingSite = (System.String)fieldValue; break;
			case 12: this.LocationId = (System.Nullable<long>)fieldValue; break;
			case 13: this.Note = (System.String)fieldValue; break;
			case 14: this.Phone = (System.String)fieldValue; break;
			case 15: this.PresentmentCurrency = (System.String)fieldValue; break;
			case 16: this.ReferringSite = (System.String)fieldValue; break;
			case 17: this.SourceName = (System.String)fieldValue; break;
			case 18: this.SubtotalPrice = (System.Nullable<double>)fieldValue; break;
			case 19: this.TaxesIncluded = (System.Nullable<bool>)fieldValue; break;
			case 20: this.Token = (System.String)fieldValue; break;
			case 21: this.TotalDiscounts = (System.Nullable<double>)fieldValue; break;
			case 22: this.TotalDuties = (System.Nullable<double>)fieldValue; break;
			case 23: this.TotalLineItemsPrice = (System.Nullable<double>)fieldValue; break;
			case 24: this.TotalPrice = (System.Nullable<double>)fieldValue; break;
			case 25: this.TotalTax = (System.Nullable<double>)fieldValue; break;
			case 26: this.TotalWeight = (System.Nullable<double>)fieldValue; break;
			case 27: this.AbandonedCheckoutId = (System.Nullable<long>)fieldValue; break;
			case 28: this.UpdatedAt = (System.Nullable<long>)fieldValue; break;
			case 29: this.UserId = (System.Nullable<long>)fieldValue; break;
			case 30: this.TenantId = (System.Int32)fieldValue; break;
			case 31: this.StoreId = (System.Int32)fieldValue; break;
			case 32: this.Remark = (System.String)fieldValue; break;
			case 33: this.Status = (System.String)fieldValue; break;
			case 34: this.AssigneeId = (System.Int32)fieldValue; break;
			case 35: this.CallTimes = (System.Int32)fieldValue; break;
			case 36: this.AbandonedOrderId = (System.String)fieldValue; break;
			case 37: this.StatusId = (System.Int32)fieldValue; break;
			case 38: this.RemarkId = (System.Int32)fieldValue; break;
			case 39: this.AssigningDate = (System.Nullable<long>)fieldValue; break;
			case 40: this.ShippingAddressId = (System.Nullable<long>)fieldValue; break;
			case 41: this.BillingAddressId = (System.Nullable<long>)fieldValue; break;
			case 42: this.AdditionalInfo = (System.String)fieldValue; break;
			case 43: this.FullBillingAddress = (System.String)fieldValue; break;
			case 44: this.FullShippingAddress = (System.String)fieldValue; break;
			case 45: this.CustomerName = (System.String)fieldValue; break;
			case 46: this.CreationTime = (System.Nullable<long>)fieldValue; break;
			case 47: this.Products = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
